class_based_view/class_based_view/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

class_based_view/store/urls.py
from django.urls import URLPattern, path

from .views import (
  BookCreateView, BookDeleteView, BookRedirectView, IndexView, BookDetailView,
  BookListView, BookCreateView, BookUpdateView, BookFormView, BookRedirectView
)
from django.views.generic.base import RedirectView, TemplateView

app_name = 'store'

urlpatterns = [
  path('about/', IndexView.as_view(), name='about'),
  path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
  path('celemony_info/', TemplateView.as_view(template_name='celemony_info.html'), name='celemony_info'),
  path('book_detail/<int:pk>', BookDetailView.as_view(), name='book_detail'),
  path('book_list/', BookListView.as_view(), name='book_list'),
  path('book_list/<name>', BookListView.as_view(), name='book_list'),
  path('book_add/', BookCreateView.as_view(), name='book_add'),
  path('book_update/<int:pk>', BookUpdateView.as_view(), name='book_update'),
  path('book_delete/<int:pk>', BookDeleteView.as_view(), name='book_delete'),
  path('book_form/', BookFormView.as_view(), name='book_form'),
  path('google/', RedirectView.as_view(url='https://google.co.jp')),
  path('book_redirect_view/', BookRedirectView.as_view(), name='book_redirect_view'),
  path('book_redirect_view/<int:pk>', BookRedirectView.as_view(), name='book_redirect_view'),
]

class_based_view/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

class_based_view/templates/about.html
{% comment %} <h1>Indexページです</h1>
<form method="POST">
{% csrf_token %}
{{ book_form.as_p }}
<input type="submit" value="送信">
</form> {% endcomment %}


<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS ホームページの「はじめに」からコピペ-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>

    <body style="padding-top:50px">
        <div class="container mt-3">

            <div class="accordion" id="accordionExample">
              <!--ここから1セット-->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                            asdfasdfasdf
                        </button> 
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne">
                        <div class="accordion-body">
                            <strong>asdfasdf</strong>
                        </div>
                    </div>         
                </div>

        </div>
        <!-- Bootstrap CSS ホームページの「はじめに」からコピペ-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

class_based_view/templates/book.html
{{ object.name }}<br>
{{ object.description }}<br>
{{ object.price }}円<br>

class_based_view/templates/book_add.html
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_form form %}
{% bootstrap_button button_type="submit" content="Edit" %}
{{ form.name }}
{{ form.description }}
{{ form.as_p }}
<hr>
{% comment %} {% for picture in pictures %}
  <img width="100px" height="100px" src="{{ picture.picture.url }}">
{% endfor %} {% endcomment %}
{% comment %} {{ picture_form.as_p }} {% endcomment %}
<input type="submit" value="更新">
</form>

<style>
img:hover{
  opacity: 0.2
}

class_based_view/templates/book_delete.html
<form method="POST">
{% csrf_token %}
<p>{{object.name}}を削除してもよろしいですか？</p>
<input type="submit" value="削除する">
</form>

class_based_view/templates/book_list.html
{% load static %}

{% comment %} <h1>Home画面です</h1>

<h2><a href="{% url 'store:celemony_info' %}"> Celemony Infomation</h2>
<h2><a href="{% url 'store:book_list' %}"> Communication</h2> {% endcomment %}


<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta>
    <title>個人サイト向け 無料ホームページテンプレート tp_simple16</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ここにサイト説明を入れます">
    <meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">

    <!-- Bootstrap CSS ホームページの「はじめに」からコピペ-->
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> {% endcomment %}
    {% comment %} cssの読み込み {% endcomment %}

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style-opening.css' %}">
    {% comment %} <script src="static/fixmenu_pagetop.js"></script>
    <script src="static/openclose.js"></script> {% endcomment %}
    <script type="text/javascript" src="{% static 'fixmenu_pagetop.js' %}"></script>
    <script type="text/javascript" src="{% static 'openclose.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body class="book_list">
    {% comment %} <div id="container"> {% endcomment %}


    
      {% comment %} header要素のインポート {% endcomment %}
      {% include 'header_pc.html' %}
      {% include 'header_phone.html' %}

      <section class="inner first">


        <section>
          <div class="accordion">
            <a href="{% url 'store:book_add' %}" class="add-data-btn">データ追加</a>
            {% for object in object_list %}
              <div class="accordion-area">
                <p class="menu js-menu no-active">{{ object.name }}</p>
                <div class="contents">
                  {{ object.description | linebreaksbr }}
                  <br>
                  <a href="{% url 'store:book_update' object.id %}">編集</a>
                  <br>
                  <a href="{% url 'store:book_delete' object.id %}">削除</a>
                  <br>
                  {% if object.image %}
                    <a href="{{ object.image.url }}"><img width="100px" src={{ object.image.url }}></a>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        </section>


      </section>
    {% comment %} </div> {% endcomment %}



    <!--オープニングアニメーション-->
    <aside id="mainimg">
    <img src="{% static '2.png' %}" alt="" class="photo photo2">
    <img src="{% static '2.png' %}" alt="" class="photo photo2">
    <img src="{% static '2.png' %}" alt="" class="photo photo3">
    <img src="{% static '2.png' %}" alt="" class="photo photo4">
    <img src="{% static '2.png' %}" alt="" class="photo photo5">
    <img src="{% static '2.png' %}" alt="" class="photo photo6">
    <img src="{% static '2.png' %}" alt="" class="photo photo7">
    <img src="{% static '2.png' %}" alt="" class="photo photo8">
    <img src="{% static '2.png' %}" alt="" class="photo photo9">
    </aside>


    <!--更新情報の開閉処理条件設定　800px以下-->
    <script>
      {% comment %} if (OCwindowWidth() <= 800) {
        console.log('asdf');
        open_accordion("newinfo_hdr", "newinfo");
      } {% endcomment %}

      const menu = document.querySelectorAll(".js-menu");
 
      function toggle() {
        const content = this.nextElementSibling;
        this.classList.toggle("is-active");
        this.classList.toggle("no-active");
        content.classList.toggle("is-open");
      }
 
      for (let i = 0; i < menu.length; i++) {
        menu[i].addEventListener("click", toggle);
      }


    </script>

    {% comment %} <!-- Bootstrap CSS ホームページの「はじめに」からコピペ--> {% endcomment %}
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> {% endcomment %}
  </body>
</html>

class_based_view/templates/book_update.html
{% if messages %}
{% for message in messages %}
  {{ message.message }}
{% endfor %}
{% endif %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<hr>
{% comment %} {% for picture in pictures %} {% endcomment %}
  <img width="100px" height="100px" src="{{ form.image.url }}">
{% comment %} {% endfor %} {% endcomment %}
{% comment %} {{ picture_form.as_p }} {% endcomment %}
<input type="submit" value="更新">
</form>

<style>
img:hover{
  opacity: 0.2
}

class_based_view/templates/celemony_info.html
<h1>celemony_info</h1>

class_based_view/templates/header_pc.html
{% load static %}

<header>

<h1 id="logo"><a href="index.html"><img src="{% static 'logo.png' %}"></a></h1>

<!--PC用（801px以上端末）メニュー-->
<nav id="menubar">
<ul>
<li><a href="{% url 'store:celemony_info' %}"> Celemony Infomation</a></li>
<li><a href="{% url 'store:book_list' %}"> Communication</a></li>
<li><a href="{% url 'store:home' %}">Home</a></li>
<li><a href="{% url 'store:about' %}">About</a></li>
<li><a href="{% url 'store:home' %}">Gallery</a></li>
<li><a href="{% url 'store:home' %}">Link</a></li>
</ul>
</nav>

<ul class="icon">
<li><a href="#"><img src="{% static 'icon_facebook.png' %}" alt="Facebook"></a></li>
<li><a href="#"><img src="{% static 'icon_twitter.png' %}" alt="Twitter"></a></li>
<li><a href="#"><img src="{% static 'icon_instagram.png' %}" alt="Instagram"></a></li>
</ul>

</header>

class_based_view/templates/header_phone.html
<!--小さな端末用（800px以下端末）メニュー-->
<nav id="menubar-s">
<ul>
<li><a href="{% url 'store:celemony_info' %}"> Celemony Infomation</a></li>
<li><a href="{% url 'store:book_list' %}"> Communication</a></li>
<li><a href="{% url 'store:home' %}">Home</a></li>
<li><a href="{% url 'store:about' %}">About</a></li>
<li><a href="{% url 'store:home' %}">Gallery</a></li>
<li><a href="{% url 'store:home' %}">Link</a></li>
</ul>
</nav>

<!--ページの上部に戻る「↑」ボタン-->
<p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>

<!--メニュー開閉ボタン-->
<div id="menubar_hdr" class="close">
  <!--メニューの開閉処理条件設定　800px以下-->
  <script>
  if (OCwindowWidth() <= 800) {
    open_close("menubar_hdr", "menubar-s");
  }
  </script>
</div>

class_based_view/templates/home.html
{% load static %}

{% comment %} <h1>Home画面です</h1>

<h2><a href="{% url 'store:celemony_info' %}"> Celemony Infomation</h2>
<h2><a href="{% url 'store:book_list' %}"> Communication</h2> {% endcomment %}


<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta>
<title>個人サイト向け 無料ホームページテンプレート tp_simple16</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'style-opening.css' %}">
{% comment %} <script src="static/fixmenu_pagetop.js"></script>
<script src="static/openclose.js"></script> {% endcomment %}
<script type="text/javascript" src="{% static 'fixmenu_pagetop.js' %}"></script>
<script type="text/javascript" src="{% static 'openclose.js' %}"></script>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="home">

<div id="container">

{% comment %} header要素のインポート {% endcomment %}
{% include 'header_pc.html' %}

<div id="contents">

<aside><section class="inner first"><img src="{% static 'mainimg.jpg' %}" alt=""></aside>

<h2>各ページ１つ目のボックスは</h2>
<p><span class="color1">&lt;section class=&quot;inner first&quot;&gt;</span><br>
として下さい。<span class="color1">first</span>がないと、上のheaderブロックに重なってしまいます。<br>
２つ目以降のボックスは<span class="color1">&lt;section class=&quot;inner&quot;&gt;</span>のみでOKです。</p>

</section>

<section class="inner">

<h2>当テンプレートについて</h2>

<h3>当テンプレートはレスポンシブWEBデザインです</h3>
<p>パソコン、スマホ、タブレットなど、各端末サイズでレイアウトが自動で切り替わります。<br>
古いブラウザで閲覧した場合にCSSの一部が適用されない（角を丸くする加工やグラデーションなどの加工等）のでご注意下さい。</p>

<h3>各デバイスごとのレイアウトチェックは</h3>
<p>最終的なチェックは実際のタブレットやスマホで行うのがおすすめですが、臨時チェックは最新のブラウザで行う事もできます。ブラウザの幅を狭くしていくと、各端末サイズに合わせたレイアウトになります。</p>
<p>注意：cssはリアルタイムで反映されますが、javascript(js)はブラウザを再読み込みさせないと反映されないので、レイアウトが切り替わったらブラウザを再読み込みさせて下さい。javascriptは小さい端末用の開閉ブロックなどに使われています。</p>

<h3>各デバイス用のスタイル変更は</h3>
<p>cssフォルダの各cssファイルで行って下さい。詳しい説明も入っています。<br>
メインのスタイルはstyle.cssになります。<br>
前半はパソコン環境を含めた全端末の共通設定になります。中盤以降、各端末向けのスタイルが追加設定されています。<br>
media=&quot; (～)&quot;の「～」部分でcssを切り替えるディスプレイのサイズを設定しています。ここは必要に応じて変更も可能です。</p>

<h3>小さい端末（※幅800px以下）の環境でのみ</h3>
<p>メインメニューが折りたたみ式（３本バーアイコン化）になります。バーのスタイル設定もstyle.cssで行う事ができます。</p>

<h3>画像ベースは</h3>
<p>「base」フォルダに入っていますのでご自由にご活用下さい。<br>
写真の元素材を当社運営の<a href="https://photo-chips.com/">PHOTO-CHIPS</a>や<a href="https://decoruto.com/">DECORUTO</a>で配布している場合もございます。</p>

</section>

<section class="inner">

<h2>当テンプレートの使い方</h2>

<h3>初心者向けマニュアル公開中</h3>
<p>画像加工やテンプレートの編集方法、無料サーバーを使ってサイトを公開するなど動画をまじえてわかりやすく解説しています。<br>
<a href="https://template-party.com/file/" target="_blank">初心者向けマニュアルはこちら。</a></p>

<h3>注意：当テンプレートにはメインメニューが「２箇所」入っています</h3>
<p>パソコンなどの大きな端末「menubar（幅801px以上）」向けと、タブレットやスマホなどの小さな端末「menubar-s（幅800px以下）」向けがそれぞれ入っています。大きな端末向けは編集ソフトで見れると思いますが、小さな端末向けは見えないと思いますのでhtml側で編集して下さい。</p>

<h3>titleタグ、copyright、metaタグ、他の設定</h3>
<p><strong class="color1">titleタグの設定はとても重要です。念入りにワードを選んで適切に入力しましょう。</strong><br>
まず、htmlソースが見れる状態にして、<br>
<span class="look">&lt;title&gt;個人サイト向け 無料ホームページテンプレート tp_simple16&lt;/title&gt;</span><br>
を編集しましょう。<br>
あなたのホームページ名が「SAMPLE SITE」だとすれば、<br>
<span class="look">&lt;title&gt;SAMPLE SITE&lt;/title&gt;</span><br>
とすればＯＫです。SEO対策もするなら冒頭に重要なワードを入れておきましょう。</p>
<p><strong class="color1">copyrightを変更しましょう。</strong><br>
続いてhtmlの下の方にある、<br>
<span class="look">Copyright&copy; SAMPLE SITE All Rights Reserved.</span><br>
の部分もあなたのサイト名に変更します。</p>
<p><strong class="color1">metaタグを変更しましょう。</strong><br>
htmlソースが見える状態にしてmetaタグを変更しましょう。</p>
<p>ソースの上の方に、<br>
<span class="look">content=&quot;ここにサイト説明を入れます&quot;</span><br>
という部分がありますので、テキストをサイトの説明文に入れ替えます。検索結果の文面に使われる場合もありますので、見た人が来訪したくなるような説明文を簡潔に書きましょう。</p>
<p>続いて、その下の行の<br>
<span class="look">content=&quot;キーワード１,キーワード２,～～～&quot;</span><br>
も設定します。ここはサイトに関係のあるキーワードを入れる箇所です。10個前後ぐらいあれば充分です。キーワード間はカンマ「,」で区切ります。</p>
<p><strong class="color1">h1ロゴのaltタグも変更しましょう。</strong><br>
  html側に、<br>
<span class="look">alt=&quot;SAMPLE SITE&quot;</span><br>
となっている箇所があるので、この部分もあなたのサイト名に変更しましょう。</p>

<h3>上部のロゴ画像について</h3>
<p>文字なしの土台画像がbaseフォルダに入っていますのでそれにサイト名をのせてimagesフォルダに上書きして下さい。画像の大きさは自由に変更してもらっても構いませんがある程度大きくしておいた方が高解像度の端末で鮮明に見えます。</p>
<p><strong class="color1">ロゴサイズ変更は</strong><br>
cssフォルダのstyle.cssの「header #logo img」のwidthの数字で変更できます。各端末サイズごとに設定がある場合があるので注意して下さい。</p>

<h3>トップページのアニメーションについて</h3>
<p>トップページアニメーションが動くのはIE10以降です。それ以前はアニメーション終了時点での画像が固定表示されます。</p>
<p><strong class="color1">アニメーション用の画像を置き換えたい場合</strong><br>
幅と高さを700pxにすれば、テンプレートの配置バランスを保てます。<br>
画像の読み込みは、各ページ下部の、<br>
&lt;!--オープニングアニメーション--&gt;<br>
のブロックです。実は9枚全て別々の画像にする事もできるのですが、読み込みに負荷がかかるので統一した画像を使っています。<br>
配置バランスや大きさの調整などは、cssフォルダのstyle-opening.cssで行う事ができます。</p>

<h3>リストタグを使いたい場合の注意点</h3>
<p>そのままではリストマークが出ませんので、リストタグを使う場合は以下のようなスタイルを追加して下さい。</p>
<p>&lt;ul <span class="color1">class=&quot;disc&quot;</span>&gt;<br>
&lt;li&gt;リストタグ&lt;/li&gt;<br>
&lt;li&gt;リストタグ&lt;/li&gt;<br>
&lt;li&gt;リストタグ&lt;/li&gt;<br>
&lt;/ul&gt;
</p>
<p>↓出力例</p>
<ul class="disc">
<li>リストタグ</li>
<li>リストタグ</li>
<li>リストタグ</li>
</ul>
<ol>
<li>olタグはそのままででます。</li>
<li>olタグはそのままででます。</li>
<li>olタグはそのままででます。</li>
<li>olタグはそのままででます。</li>
</ol>

<h3>スクロール中に出る「↑」アイコンについて</h3>
<p>fixmenu_pagetop.jsで動作の制御を、cssフォルダのstyle.css内の<br>
/*PAGE TOP（↑）設定<br>
でボタンデザインを設定しています。<br>
ボタンの出現ポイントは、現在350pxの場所になっています。変更したい場合はfixmenu_pagetop.jsの34行目あたりにある、<br>
offsettop = 350;<br>
の350を変更して下さい。</p>

</section>

<footer>
<small>Copyright&copy; <a href="{% url 'store:home' %}">SAMPLE SITE</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

</div>
<!--/#contents-->

</div>
<!--/#container-->

<!--オープニングアニメーション-->
<aside id="mainimg">
<img src="{% static '1.png' %}" alt="" class="photo photo1">
<img src="{% static '1.png' %}" alt="" class="photo photo2">
<img src="{% static '1.png' %}" alt="" class="photo photo3">
<img src="{% static '1.png' %}" alt="" class="photo photo4">
<img src="{% static '1.png' %}" alt="" class="photo photo5">
<img src="{% static '1.png' %}" alt="" class="photo photo6">
<img src="{% static '1.png' %}" alt="" class="photo photo7">
<img src="{% static '1.png' %}" alt="" class="photo photo8">
<img src="{% static '1.png' %}" alt="" class="photo photo9">
</aside>

<!--小さな端末用（800px以下端末）メニュー-->
{% include 'header_phone.html' %}


</body>
</html>

class_based_view/templates/modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="confirmModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">データの削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>削除すると元に戻すことはできません。よろしいでしょうか？</p>
            </div>
            <div class="modal-footer">
            <form method="POST">{% csrf_token %}
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">DELETE</button>
            </div>
            </form>
        </div>
    </div>
</div>